config/routes.rb
Blocmetrics::Application.routes.draw do
  devise_for :users
  resources :applications
  get 'about' => 'welcome#about'
  get 'profile' => 'users#show'

  namespace :api do
    namespace :v1 do
      resources :clicks, only: :create
    end
  end

  root to: "welcome#index"
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  has_many :events
  has_many :clicks
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :application
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base

end

app/controllers/api/v1/clicks_controller.rb
class Api::V1::ClicksController < Api::V1::ApplicationController
  def create
    @application = Application.find(params[:application_id])
    @click = @application.clicks.new(click_params)
    if @click.save
      head 200
    else
      head 500
    end
  end

private

  def click_params
    params.require(:click).permit(:element_name, :id_name, :class_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    @applications = Application.all
  end

  def show
    @application = Application.find(params[:id])
  end

  def create
    @application = Application.new(params.require(:application))
    @application.save

    redirect_to @application
  end

  def new
    @application = Application.new
  end

  def destroy
    @application = Application.find(params[:id])
    @application.destroy
    redirect_to applications_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show

  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/index.html.haml
- @applications.each do |application|
  %h1 application

app/views/applications/show.html.haml
%h1 Events
= @application.clicks.count

%p
  :escaped
    Paste this into your <head>
  %pre
    = preserve do
      :escaped
        <script src='#{request.host_with_port}/blocmetrics.js' id='blocmetrics' data-application-id=#{@application.id}></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- NAVIGATION -->
    <ul class="nav nav-tabs" role="tablist">
      <li><%= link_to "Blocmetrics", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Applications", applications_path %></li>

      <% if current_user %>
        <li>Welcome, <%= link_to current_user.email, profile_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
  </ul>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/index.html.haml
%h1 Hello